### ISSUE TITLE
Error while launching the app in chrome in flutter 1.9

### ISSUE THREAD

**Issue by rguntha** [Baseflow/flutter_cached_network_image#279] opened 2019-10-28 06:18 UTC
PS C:\Code\MultiHazardTracker\MHTFlutter\mht_flutter> flutter run -d chrome
Downloading Web SDK...                                              2.7s
Launching lib\main.dart on Chrome in debug mode...
Error creating cached_network_image|lib/cached_network_image.ddc.dill
Error creating kernel summary for module:cached_network_image|lib/cached_network_image.ddc.dill

Response:--dart-sdk-summary=file:///C:/Code/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
--output=C:\Users\ramesh\AppData\Local\Temp\scratch_space2ab84b5d-f949-11e9-9ddc-a0d3c14bdf2f\packages\cached_network_image\cached_network_image.ddc.dill
--packages-file=file:///C:/Users/ramesh/AppData/Local/Temp/kernel_builder_3ce6be3a-f949-11e9-9ddc-a0d3c14bdf2f/.packages --multi-root-scheme=org-dartlang-app
--exclude-non-sources --summary-only --target=ddc --libraries-file=file:///C:/Code/flutter/bin/cache/flutter_web_sdk/libraries.json --reuse-compiler-result
--use-incremental-compiler --used-inputs=C:\Users\ramesh\AppData\Local\Temp\kernel_builder_3ce6be3c-f949-11e9-9ddc-a0d3c14bdf2f\used_inputs.txt
--input-summary=org-dartlang-app:///packages/flutter_cache_manager/flutter_cache_manager.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/foundation.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/widgets.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/material.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/painting.ddc.dill --input-summary=org-dartlang-app:///packages/path/path.ddc.dill
--input-summary=org-dartlang-app:///packages/path_provider/path_provider.ddc.dill --input-summary=org-dartlang-app:///packages/uuid/uuid.ddc.dill
--input-summary=org-dartlang-app:///packages/sqflite/sqflite.ddc.dill --input-summary=org-dartlang-app:///packages/http/http.ddc.dill
--input-summary=org-dartlang-app:///packages/meta/meta.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/foundation/_bitfield_web.ddc.dill
--input-summary=org-dartlang-app:///packages/vector_math/vector_math_64.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/widgets/actions.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/cupertino.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/gestures.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/semantics.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/rendering.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/animation.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/painting/_network_image_web.ddc.dill
--input-summary=org-dartlang-app:///packages/platform/platform.ddc.dill --input-summary=org-dartlang-app:///packages/uuid/uuid_util.ddc.dill
--input-summary=org-dartlang-app:///packages/crypto/crypto.ddc.dill --input-summary=org-dartlang-app:///packages/convert/convert.ddc.dill
--input-summary=org-dartlang-app:///packages/sqflite/sql.ddc.dill --input-summary=org-dartlang-app:///packages/sqflite/src/constant.ddc.dill
--input-summary=org-dartlang-app:///packages/sqflite/utils/utils.ddc.dill --input-summary=org-dartlang-app:///packages/sqflite/sqlite_api.ddc.dill
--input-summary=org-dartlang-app:///packages/sqflite/src/collection_utils.ddc.dill --input-summary=org-dartlang-app:///packages/sqflite/src/sql_builder.ddc.dill
--input-summary=org-dartlang-app:///packages/synchronized/src/basic_lock.ddc.dill --input-summary=org-dartlang-app:///packages/http/src/base_client.ddc.dill
--input-summary=org-dartlang-app:///packages/http_parser/http_parser.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_buffers.ddc.dill
--input-summary=org-dartlang-app:///packages/vector_math/hash.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/physics.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/collection.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/cupertino/action_sheet.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/src/gestures/arena.ddc.dill --input-summary=org-dartlang-app:///packages/flutter/src/semantics/binding.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/src/rendering/animated_size.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/src/animation/animation.ddc.dill --input-summary=org-dartlang-app:///packages/typed_data/typed_data.ddc.dill
--input-summary=org-dartlang-app:///packages/charcode/ascii.ddc.dill --input-summary=org-dartlang-app:///packages/pedantic/pedantic.ddc.dill
--input-summary=org-dartlang-app:///packages/string_scanner/src/eager_span_scanner.ddc.dill --input-summary=org-dartlang-app:///packages/source_span/source_span.ddc.dill
--input-summary=org-dartlang-app:///packages/flutter/src/physics/clamped_simulation.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/algorithms.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/src/utils.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/iterable_zip.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/src/comparators.ddc.dill --input-summary=org-dartlang-app:///packages/collection/src/priority_queue.ddc.dill
--input-summary=org-dartlang-app:///packages/collection/src/canonicalized_map.ddc.dill --input-summary=org-dartlang-app:///packages/charcode/charcode.ddc.dill
--input-summary=org-dartlang-app:///packages/term_glyph/src/generated/ascii_glyph_set.ddc.dill --input-summary=org-dartlang-app:///packages/charcode/html_entity.ddc.dill
--source=package:cached_network_image/src/cached_network_image_provider.dart --source=package:cached_network_image/cached_network_image.dart
--source=package:cached_network_image/src/scaled_file_image.dart --source=package:cached_network_image/src/cached_image_widget.dart
org-dartlang-app:///packages/cached_network_image/src/cached_network_image_provider.dart:53:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional
arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
org-dartlang-app:///packages/flutter/src/painting/image_provider.dart: Context: This is the overridden method ('load').
org-dartlang-app:///packages/cached_network_image/src/scaled_file_image.dart:45:24: Error: The method 'ScaledFileImage.load' has fewer positional arguments than those of
overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(ScaledFileImage key) {
                       ^
org-dartlang-app:///packages/flutter/src/painting/image_provider.dart: Context: This is the overridden method ('load').

AssetNotFoundException: cached_network_image|lib/cached_network_image.ddc.dill

AssetNotFoundException: cached_network_image|lib/cached_network_image.ddc.dill

AssetNotFoundException: cached_network_image|lib/cached_network_image.ddc.dill
Error creating mht_flutter|lib/screens/hazard_question_screen.ddc.dill
Error creating kernel summary for module:mht_flutter|lib/screens/hazard_question_screen.ddc.dill

**Comment by andermoran** [comment] 2019-10-28 13:23
Same problem here

**Comment by hoichong** [comment] 2019-10-30 07:07
We encounter the same issue, and we switch to using 2.0.0-rc, manage to fix the compile/build issue, and when we test our flutter web app, the images do not show up. It keep showing the image loading icon. Is there a problem with the way cache being implemented in Flutter Web versus cache being implemented in Mobile ?

**Comment by hoichong** [comment] 2019-10-31 05:15
Initially we did see a CORS issue, which we then fix by doing the necessary settings on our nginx that is serving those images. After that, we do not see any CORS errors but the images are still not showing up.

**Comment by hoichong** [comment] 2019-10-31 08:14
We change our code to use back the "FadeInImage class" from Flutter, and the images get loaded and displayed.

**Comment by renefloor** [comment] 2019-11-04 06:18
I'd expect that CachedNetworkImage never worked on Flutter Web. The CacheManager which stores the images and the information about the cache is not compatible with Web. You can see a start of the discussion here: https://github.com/renefloor/flutter_cache_manager/issues/122

**Comment by MoacirSchmidt** [comment] 2020-01-30 19:59
Check PR https://github.com/renefloor/flutter_cached_network_image/pull/329

**Comment by renefloor** [comment] 2020-02-21 13:40
Duplicate of #303

**Closed by renefloor** 2020-02-21 13:40 UTC
