### ISSUE TITLE
This issue occured

### ISSUE THREAD

**Issue by cgowthamanmca** [Baseflow/flutter_cached_network_image#269] opened 2019-10-17 11:26 UTC
Exception: Could not instantiate image codec.
I/flutter (11177):
I/flutter (11177): When the exception was thrown, this was the stack:
I/flutter (11177): #0      _futurize (dart:ui/painting.dart:4134:5)
I/flutter (11177): #1      instantiateImageCodec (dart:ui/painting.dart:1669:10)
I/flutter (11177): #2      ScaledFileImage._loadAsync (package:cached_network_image/src/scaled_file_image.dart:61:18)
I/flutter (11177): <asynchronous suspension>
I/flutter (11177): #3      ScaledFileImage.load (package:cached_network_image/src/scaled_file_image.dart:47:14)
I/flutter (11177): #4      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:316:48)
I/flutter (11177): #5      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:160:22)
I/flutter (11177): #6      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:316:25)
I/flutter (11177): #7      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter (11177): #8      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:313:11)
I/flutter (11177): #12     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:305:16)
I/flutter (11177): #13     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:951:20)
I/flutter (11177): #14     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:908:5)
I/flutter (11177): #15     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086:12)
I/flutter (11177): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter (11177): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (11177): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (11177): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter (11177): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter (11177): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter (11177): #22     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4910:32)
I/flutter (11177): #23     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5243:17)
I/flutter (11177): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
I/flutter (11177): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter (11177): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter (11177): #27     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
I/flutter (11177): #28     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
I/flutter (11177): #29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
I/flutter (11177): #30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
I/flutter (11177): #31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
I/flutter (11177): #32     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
I/flutter (11177): #36     _invoke (dart:ui/hooks.dart:249:10)
I/flutter (11177): #37     _drawFrame (dart:ui/hooks.dart:207:3)
I/flutter (11177): (elided 6 frames from package dart:async)
I/flutter (11177):
I/flutter (11177): Path:
I/flutter (11177): /data/user/0/com.girlsourced/cache/libCachedImageData/c2dbfbc0-f0be-11e9-b656-ad033e7623b7.html;
I/flutter (11177): charset=UTF-8
I/flutter (11177): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by renefloor** [comment] 2019-10-17 11:34
What's the url you tried?
`.../libCachedImageData/c2dbfbc0-f0be-11e9-b656-ad033e7623b7.html` this looks like you didn't try to download an image but an html page.

**Comment by OncoPower** [comment] 2019-10-17 13:44
@renefloor This is the URL that we tried to load `https://c.cfjump.com/Products/33681/72414727.jpg`

**Comment by gowtham2809** [comment] 2019-10-17 13:46
@renefloor We used the following url - `https://c.cfjump.com/Products/33681/72414727.jpg`

**Comment by renefloor** [comment] 2019-10-17 14:09
When I try to load that exact url it just loads perfectly fine, so I don't know what is going wrong. Maybe you once had a 404 page which returned a 200 with an html page instead of a 404 or something like that and than the page is cached.

**Comment by gowtham2809** [comment] 2019-10-17 16:41
@renefloor Yeah, there are some chances for that to happen. The image is being hosted behind a CDN like Cloudflare which is returning an HTML to check the caller. Something like this.
![image](https://user-images.githubusercontent.com/6001915/67029449-ef773c00-f12a-11e9-8dda-52ca1707a8ba.png)

Will this library be able to handle that?

**Comment by wsakka** [comment] 2019-10-20 12:35
@gowtham2809 and @cgowthamanmca , there is no image library built to handle this situation (it's not an HTTP redirect).  Image assets should be stored at a proper CDN like S3, especially when you have CloudFlare's DDOS protection enabled.

**Comment by nsttu** [comment] 2019-12-04 10:43
> What's the url you tried?
> `.../libCachedImageData/c2dbfbc0-f0be-11e9-b656-ad033e7623b7.html` this looks like you didn't try to download an image but an html page.

@renefloor Do you have a suggestion how to handle the sitiuation when you don't know if the url really returns image data. If there is something wrong with the response I would expect the errorWidget to be loaded.

**Comment by renefloor** [comment] 2020-02-21 13:48
Duplicate of #320

**Closed by renefloor** 2020-02-21 13:48 UTC
