### ISSUE TITLE
ImageStreamCompleter._checkDisposed

### ISSUE THREAD

**Issue by PawlikMichal25** [Baseflow/flutter_cached_network_image#785] opened 2022-10-04 14:15 UTC
I just wanted to mirror here this issue: https://github.com/flutter/flutter/issues/110953 because a couple of people pointed out that it's caused by cached_network_image library https://github.com/flutter/flutter/issues/110953#issuecomment-1262594872

I'm personally using the latest Flutter and cached_network_image versions and can confirm this issue is still happening, though I don't have repro steps

**Comment by definitelyme** [comment] 2022-10-06 22:50
Same issue here @Baseflow. Crashes mainly in Release

**Comment by atrope** [comment] 2022-10-07 15:11
Based on 
https://github.com/flutter/flutter/issues/77576
and 
https://github.com/flutter/flutter/pull/94902

I've created this:
https://github.com/Baseflow/flutter_cached_network_image/pull/777

i am publishing a new version to my users and will check if this fixes the issue.

**Comment by atrope** [comment] 2022-10-07 15:12
This commit to be specific: https://github.com/Baseflow/flutter_cached_network_image/pull/777/commits/e812bb8debb506e8715a93c9d83fd565a1ea00c6

**Comment by VincentDR** [comment] 2022-10-10 10:03
Same issue on iOS/Android with our production app.
Not able to reproduce it and only about 2/3 of our users are impacted.

**Comment by micohalvarez-dart** [comment] 2022-10-14 05:33
Any updates on the fix for this?

**Comment by sergevdz** [comment] 2022-10-14 16:21
I'm running the same issue, not able to reproduce and it seems only happens on release.
I would like to know if anyone was able to solve it on their own and how they did it?
ty

**Comment by atrope** [comment] 2022-10-14 18:00
I released my app with this fix https://github.com/Baseflow/flutter_cached_network_image/pull/777
it is Phased release and for now without errors

**Comment by EArminjon** [comment] 2022-10-18 08:11
> ### **[atrope](/atrope) ** commented [il y a 4 jours](#issuecomment-1279305837)

still no error ?

**Comment by EArminjon** [comment] 2022-10-18 08:12
> I released my app with this fix #777 it is Phased release and for now without errors

Still no error ? Do you have changed something in addition in your code or just taking this forked version and that's all ?

**Comment by atrope** [comment] 2022-10-18 15:46
Hi, I am still checking. The _checkDisposed is completely gone. We have a new one _AsyncStarStreamController.close  that i am checking

**Comment by davidmartos96** [comment] 2022-10-22 07:52
If someone is able to reproduce the issue it would be nice if he can give this PR branch a try #792  
I believe it could solve the case of using the ImageStream once it has been disposed

**Comment by renefloor** [comment] 2022-10-25 15:59
@davidmartos96 thanks for the PR. Would indeed be nice if somebody can verify it.

**Comment by ScottMacDougall** [comment] 2022-10-26 17:34
@renefloor I'm seeing thousands of events logged for this issue in my crashlytics reports, and a new version of the app pointing to the #792 branch appears to have fixed it for a subset of users I pushed the update to.

Would love to see this get published.

**Comment by silverhairs** [comment] 2022-10-31 07:46
Any update on this issue? It seems like #792 works

**Closed** 2022-11-25 14:42 UTC

**Comment by renefloor** [comment] 2022-11-25 14:48
Released as cached_network_image: ^3.2.3
