### ISSUE TITLE
Bad state: Cannot clone a disposed image

### ISSUE THREAD

**Issue by phanvanluan94** [Baseflow/flutter_cached_network_image#574] opened 2021-03-18 06:59 UTC
## 🐛 Bug Report

During debug mode, I got error as screenshot
<img width="225" alt="Screen Shot 2021-03-16 at 12 26 35" src="https://user-images.githubusercontent.com/22259333/111585413-d9731c80-87f1-11eb-9029-e59602e1c2a6.png">

### Reproduction steps

Using widget with dynamic image URLs, this issue would happen during image transition.

### Configuration

**Version:** 3.0.0-nullsafety

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment] 2021-03-18 07:44
This is a duplicate of https://github.com/Baseflow/flutter_cached_network_image/issues/513
@phanvanluan94 do you use gaplessPlayback? I suspect that's the issue (see also https://github.com/Baseflow/octo_image/issues/17)

**Comment by phanvanluan94** [comment] 2021-03-19 04:52
Thanks.

**Closed** 2021-03-19 04:53 UTC
