### ISSUE TITLE
不支持最新的flutter版本

### ISSUE THREAD

**Issue by DavidMGT** [Baseflow/flutter_cached_network_image#313] opened 2019-12-20 06:36 UTC
我的flutter是1.13.2
../../../.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);

**Comment by zav8** [comment] 2019-12-20 08:17
有新版本 2.0.0-rc.1
<https://pub.dev/packages/cached_network_image/versions/2.0.0-rc.1>

**Comment by jatin-rajput** [comment] 2019-12-20 08:32
you can solve this problem by just follow these steps:::
1-open the terminal in  vscode and run command flutter run then terminal show some error due to CachedNetworkImageProvider ... 
2-you have to follow the page of error by just clicking alt and right click..then pressed ctrl A and change into comment

**Comment by MichaelMarner** [comment] 2019-12-22 23:27
Duplicate of #270

**Closed** 2020-02-21 13:08 UTC
