### ISSUE TITLE
Unexpected behavior of CachedNetworkImage located off screen

### ISSUE THREAD

**Issue by keisuke-kiriyama** [Baseflow/flutter_cached_network_image#523] opened 2020-12-21 02:07 UTC
## 🐛 Bug Report

After upgrading flutter_cached_network_image to ver2.4.1, there seems to be a bug in handling errors of CachedNetworkImage located off screen.
For example, suppose an invalid image URL is passed to CachedNetworkImage.

<details><summary>sample code</summary>
<p>

```dart
@override
Widget build(BuildContext context) {
  return Scaffold(
    ...
    body: ListView.builder(
      itemCount: 30,
      itemBuilder: (BuildContext context, int index) {
        return CachedNetworkImage(
          imageUrl: 'https://www.$index.jpg', // this is invalid url
          errorWidget: (BuildContext context, String url, Object error) =>
              Icon(
            Icons.error,
              size: 20, // Due to its small size, all CachedNetworkImages are on the screen 
          ),
        );
      },
    ),
  );
}
```

</p>
</details>

At that time, the thrown error is passed [here](https://github.com/Baseflow/flutter_cache_manager/blob/b3abecd1aed5a78bfa8b3919b1b14623e6b01705/flutter_cache_manager/lib/src/cache_manager.dart#L154) and the following log is displayed on the console. 
This is the **correct behavior**.

<details><summary>console log</summary>
<p>

```
flutter: CacheManager: Failed to download file from https://www.0.jpg with error:
SocketException: Failed host lookup: 'www.0.jpg' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: CacheManager: Failed to download file from https://www.1.jpg with error:
SocketException: Failed host lookup: 'www.1.jpg' (OS Error: nodename nor servname provided, or not known, errno = 8)
...
flutter: CacheManager: Failed to download file from https://www.28.jpg with error:
SocketException: Failed host lookup: 'www.28.jpg' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: CacheManager: Failed to download file from https://www.29.jpg with error:
SocketException: Failed host lookup: 'www.29.jpg' (OS Error: nodename nor servname provided, or not known, errno = 8)
```

</p>
</details>

However, if the CachedNetworkImage is off the screen, as in the example below, the following log will be displayed.

<details><summary>sample code</summary>
<p>

```dart 
@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: Text('test'),
    ),
    body: ListView.builder(
      itemCount: 30,
      itemBuilder: (BuildContext context, int index) {
        return CachedNetworkImage(
          imageUrl: 'https://www.$index.jpg', // this is invalid url
          errorWidget: (BuildContext context, String url, Object error) =>
              Icon(
            Icons.error,
            // size: 20,
            size: 100, // <- Big size. As a result some are off the screen.
          ),
        );
      },
    ),
  );
}
```

</p>
</details>

<details><summary>console log</summary>
<p>

```
flutter: CacheManager: Failed to download file from https://www.0.jpg with error:
SocketException: Failed host lookup: 'www.0.jpg' (OS Error: nodename nor servname provided, or not known, errno = 8)
flutter: CacheManager: Failed to download file from https://www.1.jpg with error:
SocketException: Failed host lookup: 'www.1.jpg' (OS Error: nodename nor servname provided, or not known, errno = 8)
...

════════ (11) Exception caught by image resource service ═══════════════════════════════════════════
Failed host lookup: 'www.28.jpg' (OS Error: nodename nor servname provided, or not known, errno = 8)
════════════════════════════════════════════════════════════════════════════════════════════════════
════════ (12) Exception caught by image resource service ═══════════════════════════════════════════
Failed host lookup: 'www.29.jpg' (OS Error: nodename nor servname provided, or not known, errno = 8)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</p>
</details>

Is this the expected behavior?
This behavior was **not reproduced** in flutter_cached_network_image ver2.0.0.
I think the cause is that [FlutterError.reportError](https://github.com/flutter/flutter/blob/35c95a2fcedd53e133d9de0e29f97e7672929614/packages/flutter/lib/src/painting/image_stream.dart#L510) is called because [localErrorListeners](https://github.com/flutter/flutter/blob/35c95a2fcedd53e133d9de0e29f97e7672929614/packages/flutter/lib/src/painting/image_stream.dart#L504) are empty.

#### Additional information

- Not just SocketException, but other exceptions (eg timeout)
- Although the error is output to the console, the image of errorWidget is displayed correctly.

### Expected behavior

`FlutterError.reportError` is not called.

### Reproduction steps

<details><summary>full sample</summary>
<p>

```dart 
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      body: ListView.builder(
        itemCount: 30,
        itemBuilder: (BuildContext context, int index) {
          return CachedNetworkImage(
            imageUrl: 'https://www.$index.jpg', // this is invalid url
            errorWidget: (BuildContext context, String url, Object error) =>
                Icon(
              Icons.error,
//              size: 20,  // <- not reproduce
              size: 100, // <- reproduce
            ),
          );
        },
      ),
    );
  }
}
```

</p>
</details>

### Configuration

**Version:** 

flutter_cached_network_image ver2.4.1

Flutter 1.22.4 • channel unknown • unknown source
Framework • revision 1aafb3a8b9 (5 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment] 2020-12-21 08:26
I don't think this is wrong behavior.
I wouldn't mind that `FlutterError.reportError` is not called of course, but that the localErrorListeners are empty is correct.

The loading happens in the ImageProvider, the showing in the Image. Using an ListView.builder the widgets that are not on screen are not build, so the errorWidget cannot be made as well. When you scroll and the widget gets on screen the ImageProvider has already loaded (or failed) and thus the result is directly available for the image widget.

Normally the loading also just starts when the image widget is visible. In your example you don't have a placeholder widget and the height of the CachedNetworkImage is not fixed. Which means all 100 images are shown on screen while loading and then when the error shows most of them are pushed off screen. When you'd set the CachedNetworkImage to 100px the loading should only start for images that are on screen.

This loading process changed in 2.3.0, making it way more efficient when loading in a list.

**Comment by keisuke-kiriyama** [comment] 2020-12-21 09:13
Thank you for your reply. I understood.

There are the following cases.
1. CachedNetworkImage appears on the screen
1. Time-consuming image loading begins
1. The ListView scrolls and the CachedNetworkImage moves off the screen (localErrorListeners become empty)
1. An error occurs when loading an image (eg timeout)

Is it inevitable that `FlutterError.reportError` is called in such a case?
I send the log in `FlutterError.reportError` to Firebase Crashlytics, but I don't want to send such timeouts etc. caused by the network environment.

**Comment by renefloor** [comment] 2020-12-21 09:43
I think the only way to fix this is supply an extra listener to the ImageProvider (we would need to add that to the API), so it always has a listener. I'm not really sure why Flutter chose to do it this way. 

I'll have a look at the 'silent' property and how that is implemented by NetworkImage: https://github.com/flutter/flutter/blob/35c95a2fcedd53e133d9de0e29f97e7672929614/packages/flutter/lib/src/painting/image_stream.dart#L492

**Comment by renefloor** [comment] 2020-12-21 10:04
I'll close this as duplicate of #351, the error logging is a pain for many.

**Closed by renefloor** 2020-12-21 10:04 UTC

**Comment by dodatw** [comment] 2021-09-03 05:57
@renefloor did you implement silent mode ? We saw 90% FlutterError report from no network case (not important) in crashlytics backend. We want to filter out

**Comment by renefloor** [comment] 2021-09-03 06:01
@dodatw yes, as you can see here I pass every exception as silent. https://github.com/Baseflow/flutter_cached_network_image/blob/develop/cached_network_image/lib/src/image_provider/multi_image_stream_completer.dart#L37
