### ISSUE TITLE
Null or empty string fallback

### ISSUE THREAD

**Issue by ayazthemre** [Baseflow/flutter_cached_network_image#533] opened 2021-01-01 11:16 UTC
Hello,

I am trying to use this package on my project and I am using Cubits for state management. When I try to first load loading widget and then real widget I need to pass empty string to the imageUrl. This throws an exception. How should I get around ? 

```
imageUrl: widget.userData == null
                  ? ""
                  : widget.userData.pictureUrl,
```

**Comment by nickolight** [comment] 2021-04-08 13:47
The same issue. Are there some changes?

**Comment by ayazthemre** [comment] 2021-04-10 18:33
> The same issue. Are there some changes?

Not on my side. You can not load widget with null value.

**Comment by renefloor** [comment] 2021-04-30 12:24
You can easily do something like this:
```
class ImageWidget extends StatelessWidget {
  final String url;

  const ImageWidget({Key key, this.url}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return url == null
        ? PlaceholderWidget()
        : CachedNetworkImage(
            imageUrl: url,
            placeholder: (context, url) => PlaceholderWidget(),
          );
  }
}
```

Also duplicate of #314

**Closed by renefloor** 2021-04-30 12:24 UTC
