### ISSUE TITLE
Enable/Disable caching

### ISSUE THREAD

**Issue by TarekMedhat** [Baseflow/flutter_cached_network_image#345] opened 2020-03-07 22:08 UTC
## 🚀 Feature Requests

Sometimes I need to get the benefit of cachednetworkimage such as placeholder and error widget without caching the images on disk.
So would be great if there is a bool that widget takes as a parameter that enables/disables caching

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment] 2020-03-20 10:05
duplicate of #22

**Closed by renefloor** 2020-03-20 10:05 UTC
