### ISSUE TITLE
app crashes when reuse the CachedNetworkImage on real device (iphone X 12.4)

### ISSUE THREAD

**Issue by Kitty-Wong** [Baseflow/flutter_cached_network_image#215] opened 2019-07-26 04:48 UTC
the app is fine when i enter a page using CachedNetworkImage(streambuilder->gridview.builder)
but when i leave that page and enter it again (not every time... sometime need do that 3-4 time ) 
the app will crash...
the console only display lost connection to the device......

**Comment by renefloor** [comment] 2019-08-14 16:01
Can you give me a concrete minimal example on which to reproduce and can you say on which device(s) you get this behaviour?

**Comment by rongshuizhou** [comment] 2019-09-19 05:29
I have the same problem, how did you solve it?

**Comment by adsellor** [comment] 2019-11-01 13:47
+ 1 here, the issue is still present on real devices (tested on android 9 and 10). The thing I've noticed, is that app rarely crashes on the first fetch, it usually happens when the page is revisited, and CachedNetworkImage tries to get images from the cache.

**Comment by yogesh07-ios** [comment] 2020-02-27 06:48
> lost connection to the device

i have also facing the issue

**Comment by renefloor** [comment] 2020-05-21 12:38
I guess this should be fixed in 2.3.0-beta, maybe you can verify this?

**Closed** 2020-06-04 13:33 UTC
Labels: status: fixed?
