### ISSUE TITLE
Channel stable, v1.12.13+hotfix.5    Incompatible

### ISSUE THREAD

**Issue by wang-zeqi** [Baseflow/flutter_cached_network_image#308] opened 2019-12-16 06:10 UTC
cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);

**Comment by arnold-parge** [comment] 2019-12-16 08:31
Looks like it is resolved in `2.0.0-rc`.
https://pub.dev/packages/cached_network_image/versions/2.0.0-rc#-installing-tab-

**Comment by MichaelMarner** [comment] 2019-12-17 00:16
Duplicate of #270

**Closed** 2020-02-21 13:15 UTC
