### ISSUE TITLE
Option to disable errors/logs

### ISSUE THREAD

**Issue by Tetracyl** [Baseflow/flutter_cached_network_image#585] opened 2021-04-10 01:03 UTC
## 🚀 Feature Requests

An option to disable logs and errors since I'm getting spammed this error over and over again and it's taking up my whole console. My error widget is working completely fine so it would be nice if I can disable this error somehow.

```
I/flutter (10101): CacheManager: Failed to download file from https://cdn.discordapp.com/avatars/424606447867789312/58e26cd720175407ef3701eebf85713d.png?size=256 with error:
I/flutter (10101): HttpException: Invalid statusCode: 404, uri = https://cdn.discordapp.com/avatars/424606447867789312/58e26cd720175407ef3701eebf85713d.png?size=256
I/flutter (10101): CacheManager: Failed to download file from https://cdn.discordapp.com/avatars/356065937318871041/edafefc7cceacc69bf431cf1fb5765ec.jpg?size=128.png?size=256 with error:
I/flutter (10101): HttpException: Invalid statusCode: 404, uri = https://cdn.discordapp.com/avatars/356065937318871041/edafefc7cceacc69bf431cf1fb5765ec.jpg?size=128.png?size=256
I/flutter (10101): CacheManager: Failed to download file from https://cdn.discordapp.com/avatars/436212260587831316/d0bf720300ef91554e263515e8371be1.png?size=256 with error:
I/flutter (10101): HttpException: Invalid statusCode: 404, uri = https://cdn.discordapp.com/avatars/436212260587831316/d0bf720300ef91554e263515e8371be1.png?size=256
I/flutter (10101): CacheManager: Failed to download file from https://cdn.discordapp.com/avatars/669228505128501258/131be56b965a22ab48cb6966aec0bfda.png?size=256 with error:
I/flutter (10101): HttpException: Invalid statusCode: 404, uri = https://cdn.discordapp.com/avatars/669228505128501258/131be56b965a22ab48cb6966aec0bfda.png?size=256
```

**Comment by aboutlan** [comment] 2021-04-13 02:55
I have similar issues. There's a lot of this kind of error have uploaded Firebase.

**Comment by dolphinxx** [comment] 2021-04-23 06:43
These logs are from flutter_cache_manager, hard coded in [cache_manager.dart#L153](https://github.com/Baseflow/flutter_cache_manager/blob/3bd49b866d9b5e6ce09d2283f0ef97488be97e1d/flutter_cache_manager/lib/src/cache_manager.dart#L153)

Hope flutter has a better logging.

**Comment by renefloor** [comment] 2021-04-30 11:47
closing as duplicate of #351
I'm aware logging needs to improve

**Closed by renefloor** 2021-04-30 11:47 UTC
