### ISSUE TITLE
How to repeat image loading?

### ISSUE THREAD

**Issue by pro100svitlo** [Baseflow/flutter_cached_network_image#240] opened 2019-09-10 06:26 UTC
In case network was unavailable, I create `errorWidget`.
I wanna provide mechanism (maybe with btn click), so user can repeat loading of the image.

Also it might be nice to have kind of `autoRepeat` function, wich will try to repeat loading of image (in case of error) when network became available again.

**Comment by renefloor** [comment] 2020-02-21 14:20
duplicate of #306 and #41

**Closed by renefloor** 2020-02-21 14:20 UTC
