### ISSUE TITLE
dynamic url can't cache

### ISSUE THREAD

**Issue by iosyaowei** [Baseflow/flutter_cached_network_image#212] opened 2019-07-25 05:08 UTC
i want cache url like this:
http://it-resource-exchange.remember.566.sh/e62ce322-9b92-4244-9a79-7d5f045dba26.jpg?e=1564034639&token=mVuSAM3tG9YNey0dIOLbHgEPdD4aU6ynbtp_iayO:PYNQV66p_8CzrZiYS4nQZE2xmDs=

 e , token value is dynamic, cache key should be http://it-resource-exchange.remember.566.sh/e62ce322-9b92-4244-9a79-7d5f045dba26.jpg，It's wrong to use a full url.

i want kown how to custom define cache key???  

thanks

**Comment by renefloor** [comment] 2019-08-14 16:04
You can change the CacheManager with a own implementation of the BaseCacheManager and change the FileFetcher.

**Comment by mickyliu945** [comment] 2019-10-07 20:34
Same question, the FileFetcher code as follow, but i can't find any solution,
`static Future<FileFetcherResponse> _customHttpGetter(String url, {Map<String, String> headers}) async {
    Response response = await http.get(url, headers: headers);
    return HttpFileFetcherResponse(response);
  }`

**Comment by yeahydq** [comment] 2019-12-30 00:41
@renefloor, any example for implement of BaseCacheManager and FileFetcher ? Thanks

**Comment by renefloor** [comment] 2020-06-04 13:38
Sorry for the late response, but you can see an example with the firebase cache manager: https://github.com/Baseflow/flutter_cache_manager/tree/develop/flutter_cache_manager_firebase/lib/src

Closing this as duplicate of #265.

**Closed by renefloor** 2020-06-04 13:38 UTC
Labels: type: enhancement
