### ISSUE TITLE
Image blinks while scrolling.

### ISSUE THREAD

**Issue by pouloghost** [Baseflow/flutter_cached_network_image#274] opened 2019-10-21 06:37 UTC
When using io.flutter.embedding.engine.FlutterEngine and changing widget height with gesture, image blinks( quickly changing between shown and hidden status). all becomes normal when changing back to Image widget.
flutter 1.7.8 hotfix4

**Comment by cbenhagen** [comment] 2019-10-24 11:45
Possibly a duplicate of #258 ?

**Comment by renefloor** [comment] 2020-02-21 13:47
probably fixed with #289, that is merged into develop (not yet master or release). If it is not fixed please reopen the issue.

**Closed by renefloor** 2020-02-21 13:47 UTC
