### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by jasoncheng** [Baseflow/flutter_cached_network_image#424] opened 2020-07-02 08:56 UTC
## 💬 Questions and Help

When i try to set image (GIF) as background , it seems toke lot of CPU usage, 
Is that i did something wrong ?

Device: Mi A2 (mobile)   • 10.33.29.102:5555 • android-arm64  • Android 10 (API 29)

Any help please,
Thanks

- Source

```
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) => Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        title: Text(widget.title),
        elevation: 0,
        backgroundColor: Colors.transparent,
      ),
      backgroundColor: Colors.transparent,
      body: Stack(
        children: [
          Container(
              decoration: BoxDecoration(
                  image: DecorationImage(
                      image: CachedNetworkImageProvider(
                          'https://i1.kknews.cc/SIG=1isfot9/ctp-vzntr/EPwG7AQSrd0thI.jpg'),
                      fit: BoxFit.cover))),
          Center(
            child: Text(
              'You have pushed the button this many times:',
              style: TextStyle(color: Colors.red),
            ),
          )
        ],
      ));
}


```

- flutter doctor
```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.115, on Mac OS X 10.15.5 19F101, locale zh-Hant-TW)
    • Flutter version 1.20.0-3.0.pre.115 at /Users/XXX/flutter
    • Framework revision 0bffc8a391 (22 hours ago), 2020-07-01 07:08:02 -0400
    • Engine revision 712f619737
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/XXXX/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/XXXX/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (4 available)            
    • Mi A2 (mobile)   • 10.33.29.102:5555 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos             • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server        • web-javascript • Flutter Tools
    • Chrome (web)     • chrome            • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

**Comment by renefloor** [comment] 2020-07-02 08:58
@jasoncheng is this different when you use NetworkImage?

**Comment by jasoncheng** [comment] 2020-07-02 09:00
> @jasoncheng is this different when you use NetworkImage?

same 😭, is that i should report to flutter issue.

(looking for a solution...)

**Comment by renefloor** [comment] 2020-07-02 09:06
Not sure if it is really a Flutter issue or the image is just really heavy, but I think it is better to report an issue to the Flutter repo indeed. As it is not really related to CachedNetworkImage, but how Flutter shows the image I'll close this bug. 

Did you already check the CPU performance in release mode as well?

**Closed by renefloor** 2020-07-02 09:06 UTC

**Comment by jasoncheng** [comment] 2020-07-02 09:35
> Not sure if it is really a Flutter issue or the image is just really heavy, but I think it is better to report an issue to the Flutter repo indeed. As it is not really related to CachedNetworkImage, but how Flutter shows the image I'll close this bug.
> 
> Did you already check the CPU performance in release mode as well?

Yes, i did try in release/profile mode, i would report this issue to flutter repo, thanks

**Comment by MartinMacek** [comment] 2020-07-02 11:50
I used CachedNetworkImage for hundreds/thousands of network images and it seems to consume a lot of CPU mainly when the source url was 502 - bad gateway. When I replace it with Image.network(), the issue is gone but the image is just not showing. Might help...
