### ISSUE TITLE
Memory Issue (huge RAM consumption) App Crashed!.

### ISSUE THREAD

**Issue by duraibabu14** [Baseflow/flutter_cached_network_image#587] opened 2021-04-13 12:39 UTC
### Expected behavior
When there are more images loaded into cached_network_image inside a listview.builder(), while scrolling, the RAM consumption gets increased a lot and at some point the app crashed because of RAM fully occupied.

The expected behavior is less consumption of RAM when more images are loaded.

### Reproduction steps
Here Reproduction Repo : https://github.com/duraibabu14/listview.git

### Configuration
Device name : POCO F1, 
RAM : 6gb,
OS Version : MIUI 12,
Android Version : 10,

You can find my flutter doctor below :

[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.867], locale en-IN)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (4 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\DuraiBabu\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\DuraiBabu\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\DuraiBabu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (1 available)
    • POCO F1 (mobile) • android-arm64 • Android 10 (API 29)

**Version:** 3.0.0 

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

Here is the Memory Dump snap, bitmap size consumes more.

![dump](https://user-images.githubusercontent.com/72780322/114554718-a69f3580-9c84-11eb-98cb-d9dffec30229.png)

**Comment by renefloor** [comment] 2021-04-30 11:44
I'm aware of possible memory issues. You are loading a lot of really big images here. 
You can really easy reduce the memory usage by indicating how large you want your images to be kept in memory, not the line `memCacheHeight: 200,`

```
  Widget getAll(String url) {
    return SizedBox(
      height: 200,
      width: 200,
      child: CachedNetworkImage(
        height: 200,
        width: 200,
        memCacheHeight: 200,
        imageUrl: url,
        placeholder: (context, url) => CircularProgressIndicator(),
        errorWidget: (context, url, error) => Icon(Icons.error),
      ),
    );
  }
```
The same rendered image can be changed in size, so therefore the normal height and width is not used for decoding the image. By fixing the memCacheHeight you largely reduce the memory footprint of the images. However, when you want to show the photo larger later the image will need to be decoded again.

Im closing this as duplicate of #429, if you have more questions you can ask them there.

**Closed by renefloor** 2021-04-30 11:44 UTC
