### ISSUE TITLE
Image in gridview not loading after refreshing the data.

### ISSUE THREAD

**Issue by alenthomas678** [Baseflow/flutter_cached_network_image#457] opened 2020-09-04 04:14 UTC
I am using the latest version of flutter packages, connectivity and cached_network_image. I am fetching data containing images and text from an API and showing it in gridview.builder. There is no problem loading images and I have included error widget for cached network image. And while I am loading If I switched off my network and restarts the net again, the not loaded images still shows the error widget and it is not loaded at any time. But when I scroll down further the images there becomes loaded but the images which rendered error widget is still not showing its content. Can any one help me with this  issue.

**Comment by renefloor** [comment] 2020-09-04 06:51
I think this is a duplicate of #451. The imageprovider doesn't retry loading the image.

**Closed by renefloor** 2020-09-04 06:51 UTC

**Comment by alenthomas678** [comment] 2020-09-04 09:45
Why did you close this issue. I didn't get an answer yet. This is not a good practice.
