### ISSUE TITLE
Could not instantiate image codec.

### ISSUE THREAD

**Issue by cgowthamanmca** [Baseflow/flutter_cached_network_image#379] opened 2020-05-06 10:40 UTC
when below url not working 
http://www.pedroshoes.com/media/catalog/product/p/w/pw4-15940068-01-01.jpg

I/flutter (21744):
I/flutter (21744): When the exception was thrown, this was the stack:
I/flutter (21744): #0      _futurize (dart:ui/painting.dart:4304:5)
I/flutter (21744): #1      instantiateImageCodec (dart:ui/painting.dart:1682:10)
I/flutter (21744): #2      PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:88:12)
I/flutter (21744): #3      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:653:24)
I/flutter (21744): <asynchronous suspension>
I/flutter (21744): #4      FileImage.load (package:flutter/src/painting/image_provider.dart:638:14)
I/flutter (21744): #5      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:327:17)
I/flutter (21744): #6      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:160:22)
I/flutter (21744): #7      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:325:84)
I/flutter (21744): #8      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter (21744): #9      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:323:11)
I/flutter (21744): #13     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:315:16)
I/flutter (21744): #14     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1010:20)
I/flutter (21744): #15     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:967:5)
I/flutter (21744): #16     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
I/flutter (21744): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (21744): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (21744): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (21744): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (21744): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (21744): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (21744): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (21744): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (21744): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (21744): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter (21744): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (21744): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (21744): #29     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5219:32)
I/flutter (21744): #30     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (21744): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (21744): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (21744): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (21744): #34     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (21744): #35     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (21744): #36     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (21744): #37     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (21744): #38     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (21744): #39     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (21744): #43     _invoke (dart:ui/hooks.dart:259:10)
I/flutter (21744): #44     _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (21744): (elided 6 frames from package dart:async)
I/flutter (21744):
I/flutter (21744): Path:
I/flutter (21744): /data/user/0//cache/libCachedImageData/47e36720-8f81-11ea-a65e-5bab18f91a68.html;

**Comment by renefloor** [comment] 2020-05-06 10:51
When I post that url in postman it indeed returns a webpage instead of an image, so it is a duplicate of #320.

This is part of the response: 
```
<h2>This website is using a security service to protect itself from online attacks.</h2>
<p>
	This process is automatic, you will be redirected to the requested URL once the validation
	process is complete.
</p>
```
so the page is part of the security of the website. If you're the owner of that site you should fix that, otherwise I don't think you can use that image with CachedNetworkImage.

**Closed by renefloor** 2020-05-06 10:51 UTC
