### ISSUE TITLE
File is empty and cannot be loaded as an image

### ISSUE THREAD

**Issue by fryette** [Baseflow/flutter_cached_network_image#373] opened 2020-04-23 09:06 UTC
## 🐛 Bug Report

Start experience issue when file cannot be loaded from cache.

line of code where error happened:
`throw StateError('$file is empty and cannot be loaded as an image.');`

```
Bad state: LocalFile: '/Library/Developer/CoreSimulator/Devices/0F13284F-BFAF-4D83-B24A-9F5960D56635/data/Containers/Data/Application/0B6716A4-C4A3-4744-B8B7-B8DAD0256755/Library/Caches/libCachedImageData/103aac20-74d8-11ea-f119-8ffed2134f6f.png' is empty and cannot be loaded as an image.

When the exception was thrown, this was the stack
#0      FileImage._loadAsync 
package:flutter/…/painting/image_provider.dart:861
<asynchronous suspension>
#1      FileImage.load 
package:flutter/…/painting/image_provider.dart:845
#2      ImageProvider.resolveStreamForKey.<anonymous closure> 
package:flutter/…/painting/image_provider.dart:501
#3      ImageCache.putIfAbsent 
package:flutter/…/painting/image_cache.dart:359
...
Path: /Library/Developer/CoreSimulator/Devices/0F13284F-BFAF-4D83-B24A-9F5960D56635/data/Containers/Data/Application/0B6716A4-C4A3-4744-B8B7-B8DAD0256755/Library/Caches/libCachedImageData/103aac20-74d8-11ea-f119-8ffed2134f6f.png
```

### Expected behavior
The error should be handled in the lib

### Reproduction steps
Somehow my local cache was invalidated.

### Configuration

**Version:** 2.1.0, 2.0.0

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment] 2020-04-23 09:23
Does the app crash, or just doesn't show an image?

**Comment by fryette** [comment] 2020-04-23 10:01
@renefloor Not crash but showed without error widget, what is critical.
For me, the best solution is clear cache and load by url

**Comment by fryette** [comment] 2020-04-23 10:08
@renefloor Also the issue is that debugger catch this breakpoint and stop debugging, what is too annoying.

**Comment by renefloor** [comment] 2020-04-30 10:31
Than it is a duplicate of #320. I'm making some progress on that.

**Closed by renefloor** 2020-04-30 10:31 UTC

**Comment by fryette** [comment] 2020-04-30 14:24
@renefloor Thx! The new version with fix very appreciated.

**Comment by parsadoc** [comment] 2021-07-15 08:33
this worked for me
Just uninstall then reinstall the app to clear empty or damaged file from app path in device.
