### ISSUE TITLE
Exception: Could not instantiate image codec.

### ISSUE THREAD

**Issue by amitjangid80** [Baseflow/flutter_cached_network_image#427] opened 2020-07-10 08:25 UTC
## 🐛 Bug Report

I get this error while loading images using this plugin. The image is loading from the url, but when I close the app and open again then I get this error. The images are loaded and displaying properly but after closing and re-opening the app I get these error.

Exception: Could not instantiate image codec.

When the exception was thrown, this was the stack:
#0 _futurize (dart:ui/painting.dart:4304:5)
#1 instantiateImageCodec (dart:ui/painting.dart:1682:10)
#2 PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:88:12)
#3 FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:653:24)

...
Path: /data/user/0/appPackageName/cache/libCachedImageData/e65291e0-c273-11ea-918b-35fb95148e5f.jpg

### Expected behavior
Images should load properly even

### Reproduction steps
I open the app the images are displaying and loaded properly. Then after closing the app and opening the app again the same images which were displayed and loaded properly are not visible any more. Sometimes it loads half black or white images and the error widget also doesn't appear it stays with white background.

### Configuration

Version: ^2.2.0+1

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by renefloor** [comment] 2020-07-10 08:30
@amitjangid80 For me to reproduce it I at least need to have an url of the image.
Could you check if it is fixed in 2.3.0-rc? (You need the Flutter beta channel for that.)

**Comment by amitjangid80** [comment] 2020-07-11 05:02
@renefloor Actually I'm using an api to get images. The api which I'm Using returns image directly, So, for Url I'm passing the Api directly and it shows images, but sometimes it is not showing images and gives this error.. Unfortunately I can't provide that API.

**Comment by renefloor** [comment] 2020-07-13 05:43
@amitjangid80 I understand you can't switch to beta for a release, but can you check for me if the bug also occurs on beta?
If you can't give me the image urls I'm can't really help you and you have to debug yourself what's going wrong here. If you find a concrete bug I can fix it for you.

**Comment by artem-bakuta** [comment] 2020-08-19 09:42
Same issue, if i get url that is not direct image path. ErrorWidget not called, just for 404 and 403 cases (

**Comment by renefloor** [comment] 2020-10-30 10:51
@artem-bakuta 2.3.x is already out of beta. Do you still have this issue with version 2.3.3? Now also the Exception: Could not instantiate image codec should result in an error widget.

**Comment by osmanrami** [comment] 2020-12-11 23:59
Hello, I'm using version 2.4.1 and I have a similar problem when loading images from cache, It seems to be an encoding problem, although it shows the images correctly, here is the log of an image I'm trying to get from : http://havaweb.fr/files/havapro/provider_locals/-LSH5fmOHrGFKxSee7fE/300-202011241537085fbd1a94.png

LOG:

`flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
flutter: The following _Exception was thrown resolving an image codec:
flutter: Exception: Invalid image data
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _futurize (dart:ui/painting.dart:4856:5)
flutter: #1      ImageDescriptor.encoded (dart:ui/painting.dart:4724:12)
flutter: #2      instantiateImageCodec (dart:ui/painting.dart:1721:60)
flutter: <asynchronous suspension>
flutter: #3      PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:97:12)
flutter: #4      CachedNetworkImageProvider._loadAsync (package:cached_network_image/src/image_provider/_image_provider_io.dart:97:37)
flutter: <asynchronous suspension>
flutter: #5      CachedNetworkImageProvider.load (package:cached_network_image/src/image_provider/_image_provider_io.dart:65:14)
flutter: #6      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:504:13)
flutter: #7      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:355:22)
flutter: #8      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:502:83)
flutter: #9      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:108:19)
flutter: #10     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:333:9)
flutter: #11     ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:463:26)
flutter: #12     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:35)
flutter: #13     ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:460:11)
flutter: #17     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:452:16)
flutter: #18     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:330:5)
flutter: #19     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:1156:16)
flutter: #20     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1109:5)
flutter: #21     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4797:14)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #30     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #34     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #40     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
flutter: #41     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #47     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #55     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #61     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #62     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #65     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #66     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #68     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #72     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #73     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #74     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #77     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #78     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #79     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #81     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #82     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
flutter: #83     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #85     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #86     StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #91     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #92     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #93     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #96     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #97     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #98     StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #99     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #101    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #102    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #106    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
flutter: #107    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #109    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #110    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #112    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
flutter: #113    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
flutter: #114    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #116    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #117    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
flutter: #118    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #119    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
flutter: #120    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
flutter: #121    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #123    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
flutter: #124    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #125    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
flutter: #126    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #127    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #128    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #129    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #130    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #131    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #132    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #133    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #134    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
flutter: #136    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
flutter: #137    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
flutter: #138    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #139    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
flutter: #140    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
flutter: #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)`

**Closed** 2021-04-30 10:50 UTC
Labels: status: needs more info
