### ISSUE TITLE
Fail to load this image

### ISSUE THREAD

**Issue by JCKodel** [Baseflow/flutter_cached_network_image#259] opened 2019-10-05 00:27 UTC
![image](https://user-images.githubusercontent.com/379339/66246825-b9c76180-e6ed-11e9-9310-b113af95f789.png)

when trying to load this file: https://mcc-ticket.code.art.br/api/system/download?file=t842335_115f56_llx4yetr.png

**Comment by dzliergaard** [comment] 2019-10-16 19:45
Similar issue. I think at some point the query parameters are being trimmed off the url, but I'm not sure where or why.

**Comment by MichaelMarner** [comment] 2019-11-14 03:11
I take it this image nolonger exists? I get the following when trying to access:

```json
{"status":"fail","message":"Trying to get property of non-object","data":null}
```

**Comment by JCKodel** [comment] 2019-11-14 03:17
> I take it this image nolonger exists? I get the following when trying to access:
> 
> ```json
> {"status":"fail","message":"Trying to get property of non-object","data":null}
> ```

No. It doesn't exist anymore. Try this one: `https://mcc-ticket.code.art.br/api/system/download?file=t109626_b4e0c1_qgagnnv3.png`

I guess the problem is the lack of filename (please tell me you're not determining the type of image by its extension >.<)

**Comment by MichaelMarner** [comment] 2019-11-14 03:22
Same error with that image

**Comment by renefloor** [comment] 2020-02-21 13:54
I guess it is a duplicate of #320. If not please reopen with an url that gives this problem.

**Closed by renefloor** 2020-02-21 13:54 UTC
