### ISSUE TITLE
How to detect  image is loaded ? Callback for render on Complite

### ISSUE THREAD

**Issue by postflow** [Baseflow/flutter_cached_network_image#623] opened 2021-07-05 11:53 UTC
## 💬 Questions and Help
What calback help me detect what image is successfully loading ?

**Comment by zhangweiwei0326** [comment] 2021-07-20 09:54
I need…, too.

**Comment by renefloor** [comment] 2021-07-21 07:57
You can use the imageBuilder function, but there is no specific load callback at the moment.

I'm closing this issue as duplicate of #545

**Closed by renefloor** 2021-07-21 07:57 UTC
