### ISSUE TITLE
Pub.dev listing shows inconsistencies

### ISSUE THREAD

**Issue by raveesh-me** [Baseflow/flutter_cached_network_image#584] opened 2021-04-09 13:49 UTC
## 🔙 Regression
* Searching for `cached network image` not longer returns the plugin in the search results.

* the `3.0.0` no longer passes static analysis with some web function not found error.

**Comment by renefloor** [comment] 2021-04-09 14:11
![image](https://user-images.githubusercontent.com/15101411/114191806-18a61080-994d-11eb-9a24-cb2a0a18b9ca.png)

It doesn't show it when you filter on Flutter, but you do find it when search for any.


The analyzer isn't broken since 3.0.0, it is broken since web support is added. Web support is implemented similar as [NetworkImage](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/_network_image_web.dart#L89), however that doesn't have the pub.dev issues of course.

It is also an issue in the flutter repo, but it doesn't seem to have high prio: https://github.com/flutter/flutter/issues/52899.

Maybe we could try to just use NetworkImage instead of our own implementation for web. I'll close this as duplicate of #463.

**Closed by renefloor** 2021-04-09 14:11 UTC
