### ISSUE TITLE
Not loading Network Images in New Version

### ISSUE THREAD

**Issue by salman299** [Baseflow/flutter_cached_network_image#591] opened 2021-04-27 08:55 UTC
### Old (and correct) behavior
In previous versions It was working fine, It shows the image and also cheche image in memory

### Current behavior
Network Images are not loading  when giving image path to imageUrl parameter, It always show placeholder widget

### Reproduction steps
...

### Configuration
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (8 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\salma\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\salma\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.46

• No issues found!

**Version:** 1.x
 cached_network_image: ^3.0.0

**Platform:** 
- [ 8.1] :Oreo: Android

**Comment by renefloor** [comment] 2021-04-28 06:57
Without any reproduction steps this issue will be difficult to solve. The example works for me on Android, so I don't know why your version would not work.

**Comment by jjkavalam** [comment] 2021-05-01 17:09
@renefloor Hi, I seem to have the same problem reported here. Also on 3.x. Logcat doesn't seem to reveal anything interesting ... is there any way to get more verbose logs from the library ... if so, would be happy to share them here ?

**Comment by jjkavalam** [comment] 2021-05-01 18:27
I had a similar issue ... but turned out there was a missing permission in the AndroidManifest.xml

```
    <uses-permission android:name="android.permission.INTERNET"/>
```

Perhaps this is a digression from the reported issue ... but just in case this helps someone else.

**Comment by salman299** [comment] 2021-05-09 16:12
First of all Thank You for your quick response. I found an error,  when flutter_login_facebook and cached_network_image are used together, chache images didn't loads as explained in this thread.  
I have tested this several time, I hope when you try this with the latest versions you encounter same issue. 

environment:
  sdk: ">=2.12.0 <3.0.0"
flutter_login_facebook: ^1.0.1
cached_network_image: ^3.0.0

**Comment by serendipity1004** [comment] 2021-08-31 05:28
I'm experiencing the same issue. Do you know if any other version resolves this issue?

**Comment by levitanong** [comment] 2021-09-02 12:43
I ran into this too, what worked for me was just `flutter clean`, `flutter pub get`, then rerun it.

**Comment by renefloor** [comment] 2021-10-20 07:23
@GabrielAraujo could you share what your problem was?

**Comment by renefloor** [comment] 2022-01-06 07:51
@salman299 Do you still have this issue?

**Comment by jsdaniell** [comment] 2022-01-13 14:59
I'm facing this issue, my code:

```dart
             Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.circular(8),
                      child: CachedNetworkImage(
                        imageUrl: chat.firstImageOfItem,
                        fit: BoxFit.cover,
                        placeholder: (context, url) => const CircularProgressIndicator(),
                        errorWidget: (context, url, error) => const Icon(Icons.error),
                        height: 100,
                        width: 100,
                      )
                    ),
                    const SizedBox(
                      width: 8,
                    ),
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          chat.itemTitle,
                          style: const TextStyle(
                              fontSize: 18,
                              color: AllugaColors.purpleColor,
                              fontWeight: FontWeight.w600),
                        ),
                        Text(
                          chat.messages.firstWhere(
                              (element) => element["text"] != null)["text"],
                          style: const TextStyle(
                            fontSize: 15,
                            color: Colors.black54,
                          ),
                        ),
                      ],
                    ),
                    const Expanded(child: SizedBox()),
                  ],
                )
```

**Comment by salman299** [comment] 2022-01-14 07:41
@renefloor I haven't checked it again. It had solved it by removing facebook_login.

**Comment by jsdaniell** [comment] 2022-01-14 12:37
I resolved with a `flutter clean` and installing again the application on emulator.

**Comment by renefloor** [comment] 2022-01-14 13:41
In that case I'll close the issue

**Closed by renefloor** 2022-01-14 13:41 UTC
