### ISSUE TITLE
Cached Network Image error

### ISSUE THREAD

**Issue by SherryKansal** [Baseflow/flutter_cached_network_image#850] opened 2023-06-16 15:12 UTC
Because cached_network_image >=3.2.0 depends on flutter_cache_manager ^3.3.0 which depends on http ^0.13.0, cached_network_image >=3.2.0 requires http ^0.13.0.
So, because wallpaper_hub depends on both http ^1.0.0 and cached_network_image ^3.2.3, version solving failed.

I have the following pubspec.yaml file -
dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  cached_network_image: ^3.2.3
  image_gallery_saver: ^2.0.2
  permission_handler: ^10.3.0
  random_string: ^2.3.1
  dio: ^5.2.1+1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

**Comment by VKBobyr** [comment] 2023-06-18 06:21
Likely duplicate of:
https://github.com/Baseflow/flutter_cached_network_image/issues/843

**Comment by renefloor** [comment] 2023-07-23 13:00
Solved with the release of flutter_cache_manager 3.3.1

**Closed by renefloor** 2023-07-23 13:00 UTC
