### ISSUE TITLE
App Crashes when several CachedNetworkImages are being loaded

### ISSUE THREAD

**Issue by hossam-zaki** [Baseflow/flutter_cached_network_image#456] opened 2020-09-03 18:53 UTC
### Expected behavior
To load all images quickly (as they are in the cache), and the app will not crash. 
### Reproduction steps
Inside a listview.Builder(), build several cachednetworkimages at once, and view ~8 at once. For me, it will crash when on a real phone. On a simulator, it will work. 
### Configuration

**Version:** 2.2.0

**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android

**Comment by zkon** [comment] 2020-09-04 06:10
I get the same problem - I have a grid of thumbnail images and it just crashes if there are more than a certain amount (the number seems to vary). The logcat on android shows:

`2020-09-04 16:05:25.589 871-871/? E/lowmemorykiller: Kill 'com.mycompany.myapp' (31872), uid 10309, oom_adj 0 to free 2582092kB
`

Any suggestions on how to get around it?

**Comment by renefloor** [comment] 2020-09-04 06:46
I expected it to be a bit better in version 2.3.1, but apparently there is still a memory issue. If it is not a duplicate of #429 please reopen with more information.

**Closed by renefloor** 2020-09-04 06:46 UTC
