### ISSUE TITLE
Flutter v 1.12.13+hotfix.5 stable build error.

### ISSUE THREAD

**Issue by malikdoksoz** [Baseflow/flutter_cached_network_image#301] opened 2019-12-11 20:56 UTC
> Compiler message:
../../../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../flutter_src/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
../../../../.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.5.9/lib/src/asset_thumb_provider.dart:31:24: Error: The method 'AssetThumbImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(AssetThumbImageProvider key) {
                       ^
../../flutter_src/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/malikdoksoz/TumDosyalar/Dosyalar/flutter_src/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/malikdoksoz/TumDosyalar/Dosyalar/flutter_src/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 38s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by MarceloRab** [comment] 2019-12-12 02:57
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] VS Code (version 1.40.2)
[✓] Connected device (2 available)

**Comment by Masaokb** [comment] 2019-12-12 04:04
Maybe you could use rc version.
https://pub.dev/packages/cached_network_image/versions/2.0.0-rc

**Comment by purnamasari** [comment] 2019-12-12 04:06
I experience the same things when I upgraded flutter to the latest stable version, exactly v1.12.13+hotfix.5. However, the current fix is by switch your dependency:
from `cached_network_image:1.1.3` to `cached_network_image: ^2.0.0-rc`.

And also, I can see there's some other error from multi_image_picker and image_provider, maybe you should also check is there any supported version by those packages provider for this flutter version.

**Comment by korgara** [comment] 2019-12-13 18:17
Same issue after updating to the latest flutter. I think, `rc` suffix can be removed @renefloor

**Comment by MichaelMarner** [comment] 2019-12-17 00:17
Duplicate of #270

**Comment by Sandrichka22** [comment] 2019-12-17 09:45
I am experiencing the same issue. Should we expect fix soon? I cannot build my app with the new Flutter version 1.12.13+hotfix.5...

**Comment by MichaelMarner** [comment] 2019-12-17 09:47
@Sandrichka22 you can install the prerelease version `2.0.0-rc.1`

**Comment by Sandrichka22** [comment] 2019-12-17 10:13
@MichaelMarner Thanks! Will try that

**Comment by Sandrichka22** [comment] 2019-12-17 10:28
After implementing the prerelease version `2.0.0-rc.1`, I was not able to run the app and got the following error :
```
Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (20251): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
```
Then I called `WidgetsFlutterBinding.ensureInitialized();` before `runApp()`, and then the app ran successfully.
Is this service binding exception introduced somehow by the library or...?

**Comment by MichaelMarner** [comment] 2019-12-17 10:38
I don't believe `WidgetsFlutterBinding.ensureInitialized();` is required for this package - it could be caused by other initialization, especially plugin initialization in your app. What do you have in `main` before the call to `runApp`?

**Comment by korgara** [comment] 2019-12-17 10:40
@Sandrichka22 it's needed if you have any async methods calls before `runApp()` execution. It's not about this certain library, but the flutter in general.

**Comment by Sandrichka22** [comment] 2019-12-17 10:48
I have some async methods before `runApp()`. But the `WidgetsFlutterBinding.ensureInitialized();` was not required before I did the upgrade to `Flutter 1.12` and `cached_network_image` to `2.0.0-rc.1`, so that's why I was asking...

**Comment by MichaelMarner** [comment] 2019-12-18 03:26
ah ok. yeah that error is caused by the upgrade to flutter 1.12, and not related to this package.

**Comment by cleomarbrdias** [comment] 2019-12-23 14:13
> Ah ok. Sim, esse erro foi causado pela atualização para o flutter 1.12 e não está relacionado a este pacote.

e como resolver isso.. estou com o mesmo problema...

**Closed** 2020-02-21 13:19 UTC
