### ISSUE TITLE
Unhandled Exception: HttpException: No valid statuscode. Statuscode was 404

### ISSUE THREAD

**Issue by michealchow** [Baseflow/flutter_cached_network_image#223] opened 2019-08-16 14:59 UTC
I am still getting this error with cached_network_image: ^1.1.1 and the latest flutter version.
Can anyone help me to solve this?

My Flutter Doctor: I tried both master and stable channel, but got the same result

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale
    en-HK)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

```

**Comment by andynguy3n** [comment] 2019-08-17 07:45
I got the same error
`Exception: HTTP request failed, statusCode: 404`

And the widget can't build at all.

**Comment by yrom** [comment] 2019-08-23 10:51
it seems duplicated #223

**Comment by YAPPDEF** [comment] 2019-10-04 09:16
duplicate #245 #242

**Comment by renefloor** [comment] 2020-05-21 12:57
Closing as duplicate of #273

**Closed by renefloor** 2020-05-21 12:57 UTC
