### ISSUE TITLE
Web is not support

### ISSUE THREAD

**Issue by kechankrisna** [Baseflow/flutter_cached_network_image#324] opened 2020-01-20 06:39 UTC
Can  you please update to web support? I tested it either on android or ios, it was working fine except web support.

**Comment by phimath** [comment] 2020-01-25 19:56
I would also love web support.

**Comment by MoacirSchmidt** [comment] 2020-01-30 19:58
Check PR https://github.com/renefloor/flutter_cached_network_image/pull/329

**Comment by renefloor** [comment] 2020-02-21 12:54
duplicate of #303

**Closed by renefloor** 2020-02-21 12:54 UTC
